services:
  pacman:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    ports:
      - "${APP_PORT}:80"
    environment:
      - PORT=80
      - HIGH_SCORE_FILE=${HIGH_SCORE_FILE}
    volumes:
      - pacman_data:/data

volumes:
  pacman_data:
