services:
  pacman:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    ports:
      - "${APP_PORT}:80"
    environment:
      - PORT=80
